### ISSUE TITLE
Allow users to change teams

### ISSUE THREAD

**Issue by k9delight** [google/ctfscoreboard#13]
To quote,

"""
Other complexities:

What about after the game has started?
What happens to the newly-empty team, if applicable?
Is there metadata tied to a team that should be tied to players?
"""

To avoid any surprises (such as db corruption, etc) for admins, we won't allow changes after the game has started - players can create a new account then.

If the team is empty - delete applicable records. Since the game will not have started yet, there won't be any score history to cascade delete, etc.

As for meta data issues - I'll leave that up for investigation.

**Comment by zwade** [comment]
Resolved by 443b72019
