### ISSUE TITLE
Consider Removing Categories

### ISSUE THREAD

**Issue by Matir** [google/ctfscoreboard#144]
Use only tags to categorize the challenges.

I'm undecided on this, but it would simplify the DB schema and the codebase, and provide more flexibility.  Organizers looking for categories could simply assign only one tag to each challenge, thereby using the tag as a category.

**Comment by Matir** [comment]
k9delight, assigning you for discussion purposes, no need to implement yourself.  Would like your thoughts.

**Comment by Matir** [comment]
I will start working towards this in a new branch.

**Comment by k9delight** [comment]
+1 - I am for removing categories in favour of tags.
