### ISSUE TITLE
Chrome freezes when submitting flags

### ISSUE THREAD

**Issue by keesL** [google/ctfscoreboard#156]
Google Chrome (Tested with Mac and Windows, 64-bit, build 65.0.3325.181) freezes (Page Unresponsive) when submitting any flags (correct or incorrect) to the CTF Scoreboard. There is no noticeable resource constraint on the server, but the client-side tab in which the scoreboard is loaded freezes completely.

The problem can be reproduced using Chrome, but it does not seem to occur using Firefox.

No error messages are written to system logs on the server or in the client-side JavaScript console.

I am using sources code directly pulled from this GItHub repo, running on nginx on Ubuntu.

**Comment by Matir** [comment]
Sorry to hear you're running into this trouble.  I just tried on a fresh checkout of master @ 4c619ae using Chrome 65.0.3325.181 on Linux and couldn't reproduce the issue.

Do you have `PROOF_OF_WORK_BITS` set in your configuration?

If you open the Network tab of the page inspector, do you see any network requests made when submitting a flag?

**Comment by keesL** [comment]
I tweaked the uwsgi config a bit by increasing processes and threads, and I haven't had any complaints since then. It could be that my players have all switched to FF, but so far so good. I'll keep this ticket open or a few more days, but if the problem went away, I'll close it out.

`/etc/uwsgi/ctf.ini` now contains

    processes = 16
    threads = 4

To be continued...

**Comment by keesL** [comment]
No more issues observed. Not sure why increasing threads and processes server-side has a different effect on the clients, but I'll roll with it.
