### ISSUE TITLE
Feature Request - Reorder Questions

### ISSUE THREAD

**Issue by megan201296** [google/ctfscoreboard#187]
It seems that the questions appear in the order they were created. We encounter two major issues with this being the case. 1) when building out questions sometimes we want to add questions out of order (start adding the 2nd categories questions before the 1st) but then the challenges page shows the 2nd category first and 2) when we built out questions and want to add a new one in the middle of a category, we have to delete the latter questions to get the ordering right again. Not sure the best method of handling it but it would be nice to be able to easily reorder the questions, even if only from the UI perspective (drag and drop where questions are listed on the challenge page).

**Comment by Matir** [comment]
You actually *can* reorder questions, but obviously the UX is not intuitive.  If you're using the 1.x branch, go to manage the categories, and click the "challenges" button.  You'll have arrows up and down to sort the challenges.  On master, it's basically the same, but just on the single unified challenge list.

![ctf_reorder](https://user-images.githubusercontent.com/808960/39101213-7d1038d2-464b-11e8-9bb9-ab42299aac4b.png)

Please forgive the terrible challenge names :)
