### ISSUE TITLE
migration to python 3 - python 2 deprecation

### ISSUE THREAD

**Issue by noraj** [google/ctfscoreboard#271]
python2 is deprecated, any plan to move to python3 ?

https://www.python.org/doc/sunset-python-2/
https://pythonclock.org/

**Comment by Matir** [comment]
The entire codebase should be compatible with python3.  Our test suites are run against python 3.6 as well as 2.7.

**Comment by noraj** [comment]
Ok so the README is outdated:

![image](https://user-images.githubusercontent.com/16578570/73139005-66e13380-4069-11ea-9641-97f67ae2edbe.png)

**Comment by Matir** [comment]
Great catch, that was indeed outdated.  Fixed now.

**Comment by noraj** [comment]
> Great catch, that was indeed outdated. Fixed now.

It's better that than having to port the whole code to python 3. :tada:
