### ISSUE TITLE
Add solves information to /api/scoreboard for each team

### ISSUE THREAD

**Issue by k9delight** [google/ctfscoreboard#31]
It would be easier to write a chatter bot if the /api/scoreboard endpoint returned solved information (similar to /api/categories) - as we could then report on ladder changes, when challenges were solved by who, etc. 

(additionally, it means not having to mess around with /api/categories which doesn't allow anonymous access).

**Comment by Matir** [comment]
That's going to add a bit of overhead to an endpoint that gets hit a lot.  (As it is, I'm not convinced it should be added to /api/categories, I thought you were using /api/challenge?)

**Comment by k9delight** [comment]
/api/challenges will do the trick
