### ISSUE TITLE
Registering a new challenge with an answer & category does not set the answer & category properly (SQLite)

### ISSUE THREAD

**Issue by flexd** [google/ctfscoreboard#60]
Due to the other problem, I'm not sure if this is only a problem on SQLite, but when I am creating a new challenge and I fill out all the details, the category and answer are not saved to the database. I need to edit the challenge and add the category and answer again to make it stick.

**Comment by k9delight** [comment]
Hello,

I've followed the below process for testing out SQLite database.

* Added `SESSION_COOKIE_SECURE = False` to config.py
* Ran `python main.py createdb` to create the sqlite database file / tables
* Ran `python main.py` to start the database
* Created a new user (admin@example.com / admin / etc)
* Created a category called test
* Created a new challenge called test challenge. 
  * Associated the category "test" with the challenge.
  * Set points to 100
  * Set description
  * Set answer
  * Set it to unlocked

And the challenge was created successfully. That said, there was no visual confirmation that the level was created, apart from the URL changing. 

After checking the (via reloading the page / going to challenges -> edit challenge), I see the category association is still present.

As for the answer section, that will always stay blank, as the answers are hashed before being stored in the database -- thus there's nothing to show.

I'm wondering if it's a slight browser incompatibility - after creating a new level, try navigating to /api/categories, you should see something like `"cat_slug": "test",` which means the category slug has been set correctly, and try refreshing the page. 

Additionally, do you get any warnings in the browsers development console?

**Comment by k9delight** [comment]
From what I understand, this issue should be the same root cause as #59 -- arguments to Challenge.create being wrong way around for answer and category.

**Comment by flexd** [comment]
I get no errors, all the calls are HTTP 200 OK. Navigating to /api/categories I get the data you expect, but see #65 as well (weird JSON syntax).

Additionally, when I look at this challenge later, there is no box to enter an answer.

![2016-06-16-114619_1249x735_scrot](https://cloud.githubusercontent.com/assets/2317/16112548/14883cd0-33b8-11e6-8309-168438fb7e2d.png)
