### ISSUE TITLE
Py3k Support

### ISSUE THREAD

**Issue by Matir** [google/ctfscoreboard#63]
Let's support py3k.  No rush though.

**Comment by k9delight** [comment]
Random difficulty: keeping it working with AppEngine support (http://stackoverflow.com/questions/24229203/does-google-app-engine-support-python-3).

(Make both python2 and python3 work at the same time? Additional development overhead as a result, however)

**Comment by Matir** [comment]
Well, I suspect eventually GAE will support py3k.  Even if it doesn't, doing things like using python3-compatible imports and using `string.format()` instead of the string `%` operator should have negligible overhead on development but will keep us closer to py3k support?

Clearly it's not a top priority, but I do suspect that eventually the python world will finally move forward.  Of course, I also have that expectation for IPv6, DNSSEC, TLS versions, and Windows XP, so perhaps I'm just too optimistic :)

**Comment by Matir** [comment]
As of today (almost 2 years later), this is still blocked because dependencies like wsgiref do not support Python 3.  I'm going to close the issue.  If we ever get a stack that is Python3 compatible, we can move on then.

**Comment by Matir** [comment]
Library support levels:

- Flask (yes)
- Flask-RESTful (yes)
- Flask-SQLAlchemy (yes)
- Jinja2 (yes)
- MarkupSafe
- SQLAlchemy (yes)
- Werkzeug (yes)
- aniso8601 (yes)
- argparse (yes)
- itsdangerous (yes)
- pbkdf2 (yes)
- python-dateutil (yes)
- pytz (yes)
- six (yes)
- wsgiref (yes)
- Flask-Scss (yes)

Looks like we can move forward, at least based on dependencies.  It's also a good time to check if all these deps are really still useful & in use, as refactoring may have eliminated the need for one or more.
