### ISSUE TITLE
/api/page/home returns 404 and invalid JSON

### ISSUE THREAD

**Issue by flexd** [google/ctfscoreboard#65]
A GET to `/api/page/home` returns
```
)]}',
{
    "message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."
}
```

Notice the weird looking `)]}',` before the JSON object.

**Comment by flexd** [comment]
It would seem `/api/categories` also returns the invalid JSON syntax.

**Comment by flexd** [comment]
I see the weird JSON is intentional. https://github.com/google/ctfscoreboard/blob/d6fdfd966d451218553ab287918ac35060a06206/scoreboard/rest.py#L70 Nevermind that then, but it's still a 404 that happens when the front page loads. :-)

**Comment by k9delight** [comment]
Please go to /admin/page/home to create a home page. We should ship with a
suitable "please make a page here" link. Let me create a ticket.

On Thu, Jun 16, 2016 at 2:56 AM, Kristoffer Berdal <notifications@github.com

**Comment by flexd** [comment]
Oh, here I am creating all sorts of issues that are mostly my own fault :-)

**Comment by k9delight** [comment]
Well, documentation-wise it could be better. I've created #66 and #67 for short term and long term fixes for this issue -- as it could be a little more user friendly / made obvious. :)
