### ISSUE TITLE
Create a home page by default

### ISSUE THREAD

**Issue by k9delight** [google/ctfscoreboard#66]
tell people they can edit the pages using the admin account by visiting /admin/page/home, /admin/page/rules.

**Comment by flexd** [comment]
Perhaps add a "Pages" admin tool, similar to Categories and Challenges, and when there is no index page or rules page, direct the user to create them.

**Comment by k9delight** [comment]
+1, I'll ask zwade@ if he's able to do that sometime today.

**Comment by flexd** [comment]
At some point I can help out actually making some pull-requests as well, and not just issues. I'm not too familiar with Angular (I prefer React or Riot lately), but I have at least used it before I found other alternatives. I/we plan to have a CTF up and running by fall, but currently making cool challenges is more of a priority :-)

**Comment by zwade** [comment]
@flexd that's great to hear! And right now, the feedback is probably more important than actual code contributions :)
