### ISSUE TITLE
Design/CSS issues

### ISSUE THREAD

**Issue by flexd** [google/ctfscoreboard#68]
There seems to be a few CSS issues, here in Chrome Version 50.0.2661.75 (64-bit) on Ubuntu.

The content disappears under the top bar.

![2016-06-16-151241_1073x364_scrot](https://cloud.githubusercontent.com/assets/2317/16117937/eee403ca-33d4-11e6-9a2a-b4d37d5181cc.png)

It would also be nice for usability if the "Title" logo was clickable and lead to /

**Comment by zwade** [comment]
Hmm, that sidebar doesn't look right either. Is there any chance the scss didn't build properly?

**Comment by flexd** [comment]
Uh.. so it looks much better after I ran `make`.. The installation docs does not mention that :-)

**Comment by k9delight** [comment]
Yeah, the scoreboard is undergoing active development at the moment, thanks
to the effort of zwade@.

We'll need to work on the documentation soon :)

On Thu, Jun 16, 2016 at 1:05 PM, Kristoffer Berdal <notifications@github.com

**Comment by zwade** [comment]
@flexd you shouldn't have to run `make` for the scss to build, I'll look into that

**Comment by zwade** [comment]
I was unable to reproduce this. It may have just been a weird bug that has been since fixed. Will still update the documentation to explain deployment procedure.
